spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopBackend?useSSL=false
    username: root
    password: hiram
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    server:
      port: 8082

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3000/shopbackend
#    username: root
#    password: hiram
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    server: 8081

